const API_JURISLAB = "https://script.google.com/macros/s/AKfycbyFzl8x8Kazn2ek0j5N8qF0f5beYNOSrNSfxx837FEF0do_gF3lzW3Z1UCvo9eeTROB/exec";
const CHAVE_SESSAO = "JURISLAB_TOKEN";
const CHAVE_UTILIZADOR = "JURISLAB_UTILIZADOR";
function limparSessaoLocal(){localStorage.removeItem(CHAVE_SESSAO);localStorage.removeItem(CHAVE_UTILIZADOR)}
function irParaLogin(){window.location.href="login.html"}
async function validarSessao(token){const r=await fetch(API_JURISLAB+"?acao=validarSessao&token="+encodeURIComponent(token));if(!r.ok)throw new Error();return r.json()}
async function chamarApi(dados){const r=await fetch(API_JURISLAB,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(dados)});if(!r.ok)throw new Error();return r.json()}
function escaparHtml(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function mostrarMensagem(el,texto,tipo){el.textContent=texto;el.className="mensagem-formulario";if(tipo)el.classList.add(tipo)}
function casoEncerrado(c){return ["Encerrado","Concluído","Arquivado"].includes(c.estadoCaso)}
function renderizarCasos(casos,lista,resumo,accoes){
  if(!Array.isArray(casos)||!casos.length){lista.innerHTML='<div class="estado-vazio">Nenhum caso encontrado.</div>';resumo.textContent="0 casos encontrados.";return}
  resumo.textContent=casos.length+(casos.length===1?" caso encontrado.":" casos encontrados.");
  lista.innerHTML=casos.map((c,i)=>{const e=casoEncerrado(c);return `<article class="caso-cartao ${e?"caso-encerrado":""}"><div class="caso-topo"><div><h2>${escaparHtml(c.tituloCaso||"Caso jurídico")}</h2><span class="caso-codigo">${escaparHtml(c.idCaso)}</span></div><div class="caso-etiquetas"><span>${escaparHtml(c.estadoCaso||"Sem estado")}</span><span>${escaparHtml(c.prioridade||"Sem prioridade")}</span></div></div><p class="caso-descricao">${escaparHtml(c.descricaoCaso||"Sem descrição informada.")}</p><div class="caso-dados"><span><strong>Área:</strong> ${escaparHtml(c.areaDireito||"Não informada")}</span><span><strong>Utente:</strong> ${escaparHtml(c.idUtente||"")}</span><span><strong>Triagem:</strong> ${escaparHtml(c.idTriagem||"")}</span><span><strong>Responsável:</strong> ${escaparHtml(c.responsavel||"Não atribuído")}</span><span><strong>Supervisor:</strong> ${escaparHtml(c.supervisor||"Não atribuído")}</span><span><strong>Prazo:</strong> ${escaparHtml(c.prazo||"Não definido")}</span><span><strong>Abertura:</strong> ${escaparHtml(c.dataAbertura||"")}</span><span><strong>Actualização:</strong> ${escaparHtml(c.ultimaActualizacao||"")}</span></div>${c.resultado?`<div class="resultado-caso"><strong>Resultado:</strong> ${escaparHtml(c.resultado)}</div>`:""}<div class="caso-acoes"><button class="botao botao-secundario" data-accao="historico" data-indice="${i}">Ver histórico</button>${e?"":`<button class="botao botao-secundario" data-accao="consulta" data-indice="${i}">Marcar consulta</button><button class="botao botao-secundario" data-accao="encaminhar" data-indice="${i}">Encaminhar caso</button><button class="botao botao-principal" data-accao="atendimento" data-indice="${i}">Registar atendimento</button><button class="botao botao-perigo" data-accao="encerrar" data-indice="${i}">Encerrar caso</button>`}</div></article>`}).join("");
  lista.querySelectorAll("button[data-accao]").forEach(b=>b.addEventListener("click",()=>accoes[b.dataset.accao](casos[Number(b.dataset.indice)])))
}
function renderizarHistorico(itens,recipiente){if(!Array.isArray(itens)||!itens.length){recipiente.innerHTML='<div class="estado-vazio">Este caso ainda não possui atendimentos registados.</div>';return}recipiente.innerHTML=itens.map(i=>`<article class="historico-item"><div class="historico-topo"><strong>${escaparHtml(i.tipoAtendimento||"Atendimento")}</strong><span>${escaparHtml(i.dataAtendimento||"")}</span></div><p><strong>Resumo:</strong> ${escaparHtml(i.resumoAtendimento||"")}</p><p><strong>Orientação:</strong> ${escaparHtml(i.orientacaoPrestada||"")}</p>${i.proximaAccao?`<p><strong>Próxima acção:</strong> ${escaparHtml(i.proximaAccao)}</p>`:""}<div class="historico-meta"><span>${escaparHtml(i.estado||"")}</span><span>Responsável: ${escaparHtml(i.responsavel||"Não informado")}</span>${i.dataProximoContacto?`<span>Próximo contacto: ${escaparHtml(i.dataProximoContacto)}</span>`:""}</div></article>`).join("")}
addEventListener("DOMContentLoaded",async()=>{
  const token=localStorage.getItem(CHAVE_SESSAO);if(!token){limparSessaoLocal();irParaLogin();return}
  try{const s=await validarSessao(token);if(!s.sucesso||!s.valida){limparSessaoLocal();irParaLogin();return}document.getElementById("ecraValidacao").classList.add("oculto")}catch(e){limparSessaoLocal();irParaLogin();return}
  const lista=document.getElementById("listaCasos"),resumo=document.getElementById("resumoResultados"),mensagem=document.getElementById("mensagemCasos"),campo=document.getElementById("campoPesquisa"),filtro=document.getElementById("filtroEstado");
  const modAt=document.getElementById("modalAtendimento"),modHist=document.getElementById("modalHistorico"),modEnc=document.getElementById("modalEncerrar"),modEnv=document.getElementById("modalEncaminhar"),modCon=document.getElementById("modalConsulta");
  const formAt=document.getElementById("formAtendimento"),formEnc=document.getElementById("formEncerrarCaso"),formEnv=document.getElementById("formEncaminhar"),formCon=document.getElementById("formConsulta");
  const fechar=(m,f,msg)=>{m.classList.add("oculto");if(f)f.reset();if(msg)mostrarMensagem(msg,"","")};
  function abrirAtendimento(c){formAt.idCaso.value=c.idCaso||"";formAt.idUtente.value=c.idUtente||"";document.getElementById("responsavelAtendimento").value=c.responsavel||"";document.getElementById("supervisorAtendimento").value=c.supervisor||"";document.getElementById("resumoCasoSeleccionado").textContent=(c.idCaso||"")+" · "+(c.tituloCaso||"Caso jurídico");modAt.classList.remove("oculto")}
  async function abrirHistorico(c){document.getElementById("resumoCasoHistorico").textContent=(c.idCaso||"")+" · "+(c.tituloCaso||"Caso jurídico");document.getElementById("listaHistorico").innerHTML='<div class="estado-vazio">A carregar histórico...</div>';modHist.classList.remove("oculto");try{const r=await chamarApi({acao:"listarAtendimentosCaso",token,idCaso:c.idCaso});if(!r.sucesso)throw new Error(r.mensagem);renderizarHistorico(r.atendimentos||[],document.getElementById("listaHistorico"))}catch(e){document.getElementById("listaHistorico").innerHTML="";mostrarMensagem(document.getElementById("mensagemHistorico"),e.message||"Não foi possível carregar o histórico.","erro")}}
  function abrirEncerrar(c){formEnc.idCaso.value=c.idCaso||"";document.getElementById("resumoCasoEncerrar").textContent=(c.idCaso||"")+" · "+(c.tituloCaso||"Caso jurídico");modEnc.classList.remove("oculto")}
  function abrirEncaminhar(c){formEnv.idCaso.value=c.idCaso||"";formEnv.idUtente.value=c.idUtente||"";document.getElementById("responsavelEncaminhar").value=c.responsavel||"";document.getElementById("resumoCasoEncaminhar").textContent=(c.idCaso||"")+" · "+(c.tituloCaso||"Caso jurídico");modEnv.classList.remove("oculto")}
  function abrirConsulta(c){formCon.idCaso.value=c.idCaso||"";formCon.idUtente.value=c.idUtente||"";document.getElementById("responsavelConsulta").value=c.responsavel||"";document.getElementById("resumoCasoConsulta").textContent=(c.idCaso||"")+" · "+(c.tituloCaso||"Caso jurídico");modCon.classList.remove("oculto")}
  async function carregar(){resumo.textContent="A carregar casos...";mostrarMensagem(mensagem,"","");try{const r=await chamarApi({acao:"listarCasos",token,pesquisa:campo.value.trim(),estado:filtro.value});if(!r.sucesso){mostrarMensagem(mensagem,r.mensagem||"Não foi possível carregar os casos.","erro");lista.innerHTML="";resumo.textContent="";return}renderizarCasos(r.casos||[],lista,resumo,{atendimento:abrirAtendimento,historico:abrirHistorico,encerrar:abrirEncerrar,encaminhar:abrirEncaminhar,consulta:abrirConsulta})}catch(e){mostrarMensagem(mensagem,"Não foi possível contactar o servidor.","erro");resumo.textContent=""}}
  document.getElementById("formFiltros").addEventListener("submit",e=>{e.preventDefault();carregar()});filtro.addEventListener("change",carregar);document.getElementById("btnLimpar").addEventListener("click",()=>{campo.value="";filtro.value="Todos";carregar()});
  [["btnFecharModal",modAt,formAt,"mensagemAtendimento"],["btnCancelarAtendimento",modAt,formAt,"mensagemAtendimento"],["btnFecharHistorico",modHist,null,"mensagemHistorico"],["btnFecharEncerrar",modEnc,formEnc,"mensagemEncerramento"],["btnCancelarEncerramento",modEnc,formEnc,"mensagemEncerramento"],["btnFecharEncaminhar",modEnv,formEnv,"mensagemEncaminhamento"],["btnCancelarEncaminhar",modEnv,formEnv,"mensagemEncaminhamento"],["btnFecharConsulta",modCon,formCon,"mensagemConsulta"],["btnCancelarConsulta",modCon,formCon,"mensagemConsulta"]].forEach(([id,m,f,msg])=>document.getElementById(id).addEventListener("click",()=>fechar(m,f,document.getElementById(msg))));
  [modAt,modHist,modEnc,modEnv,modCon].forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.add("oculto")}));
  formAt.addEventListener("submit",async e=>{e.preventDefault();if(!formAt.checkValidity()){formAt.reportValidity();return}const d=new FormData(formAt),b=document.getElementById("btnGuardarAtendimento"),m=document.getElementById("mensagemAtendimento");b.disabled=true;b.textContent="A guardar...";try{const r=await chamarApi({acao:"registarAtendimento",token,idCaso:d.get("idCaso"),idUtente:d.get("idUtente"),tipoAtendimento:d.get("tipoAtendimento"),responsavel:d.get("responsavel"),supervisor:d.get("supervisor"),resumoAtendimento:d.get("resumoAtendimento"),orientacaoPrestada:d.get("orientacaoPrestada"),proximaAccao:d.get("proximaAccao"),dataProximoContacto:d.get("dataProximoContacto"),estado:d.get("estado"),observacoes:d.get("observacoes")});if(!r.sucesso){mostrarMensagem(m,r.mensagem||"Falha no registo.","erro");return}mostrarMensagem(m,(r.mensagem||"Atendimento registado.")+(r.idAtendimento?" Código: "+r.idAtendimento:""),"sucesso");setTimeout(()=>{fechar(modAt,formAt,m);carregar()},1200)}catch(x){mostrarMensagem(m,"Não foi possível contactar o servidor.","erro")}finally{b.disabled=false;b.textContent="Guardar atendimento"}});
  formCon.addEventListener("submit",async e=>{e.preventDefault();if(!formCon.checkValidity()){formCon.reportValidity();mostrarMensagem(document.getElementById("mensagemConsulta"),"Preencha data, hora e modalidade.","erro");return}const d=new FormData(formCon),b=document.getElementById("btnGuardarConsulta"),m=document.getElementById("mensagemConsulta");b.disabled=true;b.textContent="A agendar...";try{const r=await chamarApi({acao:"registarConsulta",token,idCaso:d.get("idCaso"),idUtente:d.get("idUtente"),dataConsulta:d.get("dataConsulta"),horaConsulta:d.get("horaConsulta"),modalidade:d.get("modalidade"),localLink:d.get("localLink"),responsavel:d.get("responsavel"),observacoes:d.get("observacoes")});if(!r.sucesso){mostrarMensagem(m,r.mensagem||"Não foi possível agendar.","erro");return}mostrarMensagem(m,(r.mensagem||"Consulta agendada.")+(r.idConsulta?" Código: "+r.idConsulta:""),"sucesso");setTimeout(()=>fechar(modCon,formCon,m),1300)}catch(x){mostrarMensagem(m,"Não foi possível contactar o servidor.","erro")}finally{b.disabled=false;b.textContent="Agendar consulta"}});
  formEnc.addEventListener("submit",async e=>{e.preventDefault();if(!formEnc.checkValidity()){formEnc.reportValidity();return}const d=new FormData(formEnc),b=document.getElementById("btnConfirmarEncerramento"),m=document.getElementById("mensagemEncerramento");b.disabled=true;b.textContent="A encerrar...";try{const r=await chamarApi({acao:"encerrarCaso",token,idCaso:d.get("idCaso"),estadoFinal:d.get("estadoFinal"),resultado:d.get("resultado"),observacoes:d.get("observacoes")});if(!r.sucesso){mostrarMensagem(m,r.mensagem||"Falha no encerramento.","erro");return}mostrarMensagem(m,r.mensagem||"Caso encerrado.","sucesso");setTimeout(()=>{fechar(modEnc,formEnc,m);carregar()},1200)}catch(x){mostrarMensagem(m,"Não foi possível contactar o servidor.","erro")}finally{b.disabled=false;b.textContent="Confirmar encerramento"}});
  formEnv.addEventListener("submit",async e=>{e.preventDefault();if(!formEnv.checkValidity()){formEnv.reportValidity();mostrarMensagem(document.getElementById("mensagemEncaminhamento"),"Preencha os campos obrigatórios.","erro");return}const d=new FormData(formEnv),b=document.getElementById("btnGuardarEncaminhamento"),m=document.getElementById("mensagemEncaminhamento");b.disabled=true;b.textContent="A registar...";try{const r=await chamarApi({acao:"registarEncaminhamento",token,idCaso:d.get("idCaso"),idUtente:d.get("idUtente"),instituicaoDestino:d.get("instituicaoDestino"),motivoEncaminhamento:d.get("motivoEncaminhamento"),pessoaContacto:d.get("pessoaContacto"),telefoneContacto:d.get("telefoneContacto"),documentoEmitido:d.get("documentoEmitido"),dataRetorno:d.get("dataRetorno"),responsavel:d.get("responsavel")});if(!r.sucesso){mostrarMensagem(m,r.mensagem||"Não foi possível registar.","erro");return}mostrarMensagem(m,(r.mensagem||"Encaminhamento registado.")+(r.idEncaminhamento?" Código: "+r.idEncaminhamento:""),"sucesso");setTimeout(()=>{fechar(modEnv,formEnv,m);carregar()},1300)}catch(x){mostrarMensagem(m,"Não foi possível contactar o servidor.","erro")}finally{b.disabled=false;b.textContent="Registar encaminhamento"}});
  carregar()
});