const API_JURISLAB="https://script.google.com/macros/s/AKfycbyFzl8x8Kazn2ek0j5N8qF0f5beYNOSrNSfxx837FEF0do_gF3lzW3Z1UCvo9eeTROB/exec";
const CHAVE_SESSAO="JURISLAB_TOKEN";
const CHAVE_UTILIZADOR="JURISLAB_UTILIZADOR";
function limparSessaoLocal(){localStorage.removeItem(CHAVE_SESSAO);localStorage.removeItem(CHAVE_UTILIZADOR)}
function irParaLogin(){location.href="login.html"}
async function validarSessao(token){const r=await fetch(API_JURISLAB+"?acao=validarSessao&token="+encodeURIComponent(token));if(!r.ok)throw new Error();return r.json()}
async function chamarApi(dados){const r=await fetch(API_JURISLAB,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(dados)});if(!r.ok)throw new Error();return r.json()}
function escapar(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function mostrar(el,texto,tipo){el.textContent=texto;el.className="mensagem-formulario";if(tipo)el.classList.add(tipo)}
function renderizar(itens,lista,resumo,abrirActualizar){
  if(!Array.isArray(itens)||!itens.length){lista.innerHTML='<div class="estado-vazio">Nenhuma consulta encontrada.</div>';resumo.textContent="0 consultas encontradas.";return}
  resumo.textContent=itens.length+(itens.length===1?" consulta encontrada.":" consultas encontradas.");
  lista.innerHTML=itens.map((i,indice)=>`<article class="consulta-cartao"><div class="consulta-topo"><div><h2>${escapar(i.dataConsulta||"Data não definida")} · ${escapar(i.horaConsulta||"")}</h2><span class="consulta-codigo">${escapar(i.idConsulta||"")}</span></div><span class="estado-etiqueta">${escapar(i.estadoConsulta||"Sem estado")}</span></div><div class="consulta-dados"><span><strong>Caso:</strong> ${escapar(i.idCaso||"")}</span><span><strong>Utente:</strong> ${escapar(i.idUtente||"")}</span><span><strong>Modalidade:</strong> ${escapar(i.modalidade||"Não informada")}</span><span><strong>Local ou link:</strong> ${escapar(i.localLink||"Não informado")}</span><span><strong>Responsável:</strong> ${escapar(i.responsavel||"Não informado")}</span><span><strong>Registo:</strong> ${escapar(i.dataRegisto||"")}</span></div>${i.observacoes?`<div class="observacoes-consulta"><strong>Observações:</strong> ${escapar(i.observacoes)}</div>`:""}<div class="consulta-acoes"><button class="botao botao-secundario" type="button" data-indice="${indice}">Actualizar consulta</button></div></article>`).join("");
  lista.querySelectorAll("button[data-indice]").forEach(b=>b.addEventListener("click",()=>abrirActualizar(itens[Number(b.dataset.indice)])))
}
addEventListener("DOMContentLoaded",async()=>{
  const token=localStorage.getItem(CHAVE_SESSAO);if(!token){limparSessaoLocal();irParaLogin();return}
  try{const s=await validarSessao(token);if(!s.sucesso||!s.valida){limparSessaoLocal();irParaLogin();return}document.getElementById("ecraValidacao").classList.add("oculto")}catch(e){limparSessaoLocal();irParaLogin();return}
  const campo=document.getElementById("campoPesquisa"),filtro=document.getElementById("filtroEstado"),lista=document.getElementById("listaConsultas"),resumo=document.getElementById("resumoResultados"),mensagem=document.getElementById("mensagemConsultas"),modal=document.getElementById("modalActualizar"),form=document.getElementById("formActualizar"),mensagemAct=document.getElementById("mensagemActualizacao"),btnGuardar=document.getElementById("btnGuardarActualizacao");
  function fechar(){modal.classList.add("oculto");form.reset();mostrar(mensagemAct,"","")}
  function abrirActualizar(i){form.idConsulta.value=i.idConsulta||"";form.estadoConsulta.value=i.estadoConsulta||"Agendada";form.responsavel.value=i.responsavel||"";form.observacoes.value=i.observacoes||"";document.getElementById("resumoConsulta").textContent=(i.idConsulta||"")+" · "+(i.idCaso||"")+" · "+(i.dataConsulta||"")+" "+(i.horaConsulta||"");modal.classList.remove("oculto")}
  async function carregar(){resumo.textContent="A carregar consultas...";mostrar(mensagem,"","");try{const r=await chamarApi({acao:"listarConsultas",token,pesquisa:campo.value.trim(),estado:filtro.value});if(!r.sucesso){mostrar(mensagem,r.mensagem||"Não foi possível carregar as consultas.","erro");lista.innerHTML="";resumo.textContent="";return}renderizar(r.consultas||[],lista,resumo,abrirActualizar)}catch(e){mostrar(mensagem,"Não foi possível contactar o servidor.","erro");resumo.textContent=""}}
  document.getElementById("formFiltros").addEventListener("submit",e=>{e.preventDefault();carregar()});filtro.addEventListener("change",carregar);document.getElementById("btnLimpar").addEventListener("click",()=>{campo.value="";filtro.value="Todos";carregar()});
  document.getElementById("btnFecharActualizar").addEventListener("click",fechar);document.getElementById("btnCancelarActualizar").addEventListener("click",fechar);modal.addEventListener("click",e=>{if(e.target===modal)fechar()});
  form.addEventListener("submit",async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const d=new FormData(form);btnGuardar.disabled=true;btnGuardar.textContent="A guardar...";try{const r=await chamarApi({acao:"actualizarConsulta",token,idConsulta:d.get("idConsulta"),estadoConsulta:d.get("estadoConsulta"),responsavel:d.get("responsavel"),observacoes:d.get("observacoes")});if(!r.sucesso){mostrar(mensagemAct,r.mensagem||"Não foi possível actualizar.","erro");return}mostrar(mensagemAct,r.mensagem||"Consulta actualizada com sucesso.","sucesso");setTimeout(()=>{fechar();carregar()},1200)}catch(x){mostrar(mensagemAct,"Não foi possível contactar o servidor.","erro")}finally{btnGuardar.disabled=false;btnGuardar.textContent="Guardar actualização"}});
  carregar()
});