const API_JURISLAB="https://script.google.com/macros/s/AKfycbyFzl8x8Kazn2ek0j5N8qF0f5beYNOSrNSfxx837FEF0do_gF3lzW3Z1UCvo9eeTROB/exec";
const CHAVE_SESSAO="JURISLAB_TOKEN";
const CHAVE_UTILIZADOR="JURISLAB_UTILIZADOR";
function limparSessaoLocal(){localStorage.removeItem(CHAVE_SESSAO);localStorage.removeItem(CHAVE_UTILIZADOR)}
function irParaLogin(){location.href="login.html"}
async function validarSessao(token){const r=await fetch(API_JURISLAB+"?acao=validarSessao&token="+encodeURIComponent(token));if(!r.ok)throw new Error();return r.json()}
async function chamarApi(dados){const r=await fetch(API_JURISLAB,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(dados)});if(!r.ok)throw new Error();return r.json()}
function escapar(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function mostrar(el,texto,tipo){el.textContent=texto;el.className="mensagem-formulario";if(tipo)el.classList.add(tipo)}
function renderizar(itens,lista,resumo){if(!Array.isArray(itens)||!itens.length){lista.innerHTML='<div class="estado-vazio">Nenhum encaminhamento encontrado.</div>';resumo.textContent="0 encaminhamentos encontrados.";return}resumo.textContent=itens.length+(itens.length===1?" encaminhamento encontrado.":" encaminhamentos encontrados.");lista.innerHTML=itens.map(i=>`<article class="encaminhamento-cartao"><div class="encaminhamento-topo"><div><h2>${escapar(i.instituicaoDestino||"Instituição não informada")}</h2><span class="encaminhamento-codigo">${escapar(i.idEncaminhamento)}</span></div><span class="estado-etiqueta">${escapar(i.estadoEncaminhamento||"Sem estado")}</span></div><p class="encaminhamento-motivo">${escapar(i.motivoEncaminhamento||"Sem motivo informado.")}</p><div class="encaminhamento-dados"><span><strong>Caso:</strong> ${escapar(i.idCaso||"")}</span><span><strong>Utente:</strong> ${escapar(i.idUtente||"")}</span><span><strong>Data:</strong> ${escapar(i.dataEncaminhamento||"")}</span><span><strong>Contacto:</strong> ${escapar(i.pessoaContacto||"Não informado")}</span><span><strong>Telefone:</strong> ${escapar(i.telefoneContacto||"Não informado")}</span><span><strong>Documento:</strong> ${escapar(i.documentoEmitido||"Não informado")}</span><span><strong>Data de retorno:</strong> ${escapar(i.dataRetorno||"Não definida")}</span><span><strong>Responsável:</strong> ${escapar(i.responsavel||"Não informado")}</span></div>${i.resultado?`<div class="resultado-encaminhamento"><strong>Resultado:</strong> ${escapar(i.resultado)}</div>`:""}</article>`).join("")}
addEventListener("DOMContentLoaded",async()=>{const token=localStorage.getItem(CHAVE_SESSAO);if(!token){limparSessaoLocal();irParaLogin();return}try{const s=await validarSessao(token);if(!s.sucesso||!s.valida){limparSessaoLocal();irParaLogin();return}document.getElementById("ecraValidacao").classList.add("oculto")}catch(e){limparSessaoLocal();irParaLogin();return}const campo=document.getElementById("campoPesquisa"),filtro=document.getElementById("filtroEstado"),lista=document.getElementById("listaEncaminhamentos"),resumo=document.getElementById("resumoResultados"),mensagem=document.getElementById("mensagemEncaminhamentos");async function carregar(){resumo.textContent="A carregar encaminhamentos...";mostrar(mensagem,"","");try{const r=await chamarApi({acao:"listarEncaminhamentos",token,pesquisa:campo.value.trim(),estado:filtro.value});if(!r.sucesso){mostrar(mensagem,r.mensagem||"Não foi possível carregar os encaminhamentos.","erro");lista.innerHTML="";resumo.textContent="";return}renderizar(r.encaminhamentos||[],lista,resumo)}catch(e){mostrar(mensagem,"Não foi possível contactar o servidor.","erro");resumo.textContent=""}}document.getElementById("formFiltros").addEventListener("submit",e=>{e.preventDefault();carregar()});filtro.addEventListener("change",carregar);document.getElementById("btnLimpar").addEventListener("click",()=>{campo.value="";filtro.value="Todos";carregar()});carregar()});